[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "igtools"
version = "0.0.2"
description = "FHIR IG Tool"
authors = [{ name = "Ronald Martins", email = "ronald.martins@gematik.de" }]
license = { file = "LICENSE" }
dependencies = [
    "beautifulsoup4==4.12.3",
    "PyYAML==6.0.2",
    "requests==2.32.3"
]

[project.scripts]
igtools = "igtools.main:main"

[igtools.setuptools]
package-dir = {"" = "src"}
packages = ["igtools"]